import Head from "next/head";
import Message from "../components/Message";

import { useEffect, useState } from "react";

import { db } from "../utils/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";

export default function Home() {
  const [allPosts, setAllPosts] = useState([]);
  useEffect(() => {
    const getPosts = async () => {
      // CRUD operation (read) firestore entry:
      const collectionRef = collection(db, "posts");
      // Creates a new immutable instance of `Query` that is extended to also -
      // include additional query constraints that are like filter criteria.
      // @param `query` — A Query instance to use as a base for new constraints.
      // @param `queryConstraints` — The list of filters to apply.
      const q = query(collectionRef, orderBy("timestamp", "desc"));
      // Attaches a listener for `DocumentSnapshot` events from our `db` that we
      // instance as a callback called `unsubscribe`, or better `snapshot`.
      // Instead of using separate getDoc/addDoc functions, we can use are -
      // `snapshot` instance of `onSnapshot` to read/write data in real-time.
      const snapshot = onSnapshot(q, (snap) => {
        // Our snap `docs` is an array of all documents in the `QuerySnapshot`.
        // With `map` we return a new array that we spread each item of data -
        // into an array object entry, that is from each firestore document.
        // console.log(snap);
        const update = snap.docs.map((doc) => ({
          ...doc.data(),
          id: doc.id,
        }));
        setAllPosts(update);
      });
      return snapshot;
    };
    getPosts();
  }, []);
  return (
    <div>
      <Head>
        <title>Creative Threads</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" my-12 text-lg font-medium">
        <h2>See what other people are saying (all posts 🐥)</h2>
        {allPosts.map((post) => (
          // Here we just spread everything we iterate as props:
          <Message key={post.id} {...post}>
            <p className="text-red-600">temp child "add buttons"</p>
          </Message>
        ))}
      </div>
    </div>
  );
}
